[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmds = [
  "mvn clean package -DskipTests"
]

[start]
cmd = "java -Dquarkus.http.port=${PORT:-8080} -Dquarkus.http.host=0.0.0.0 -jar target/quarkus-app/quarkus-run.jar"
restartPolicy = "on-failure"