[phases.setup]
nixPkgs = ["jdk23", "maven"]

[phases.build]
cmds = [
  "mvn clean package -DskipTests"
]

[phases.install]
cmds = [
  "mkdir -p target",
  "find . -name '*.jar' -type f -not -path '*/\.git/*' -not -path '*/target/dependency/*' -exec cp {} target/ \;"
]

[start]
cmd = "java -jar target/*.jar"
restartPolicy = "on-failure"